<?php
// prepended one level above the root of the site
ini_set('display_errors', 'Off');
error_reporting(0);
$nonce = base64_encode(random_bytes(17));
define('CSP_NONCE', $nonce);
// CSP for FRONT generated by wp-content/themes/$theme_secu_child/functions.php
header('X-Frame-Options: sameorigin');
header('X-XSS-Protection: 1; mode=block');
header('X-Content-Type-Options: nosniff');
header('Permissions-Policy: microphone=(), camera=(), fullscreen=(self)');
header('Referrer-Policy: strict-origin-when-cross-origin, no-referrer');
header('Strict-Transport-Security: max-age=31536000; includeSubDomains; preload');
header("Cross-Origin-Resource-Policy: same-origin");
// the following are stalled for the time to learn more about and decide whether it is suitable in the existing context
//header("Cross-Origin-Embedder-Policy: require-corp");
//header("Cross-Origin-Opener-Policy: same-origin-allow-popups");
?>
